### ISSUE TITLE
 reply[method](...).code is not a function when replying with application/json

### ISSUE THREAD

**Issue by adam-cowley** [Multicolour/multicolour-auth-jwt#1]
When replying to a failed login on POST /session with Accept:application/json, the server returns a 500 error reporting `reply[method](...).code` is not a function.

```
curl -X POST http://localhost:1811/session -d "email=adam@adam.co&password=password" -H "Accept:application/json"
{"errors":{"title":"Internal Server Error","status":500,"detail":"An internal server error occurred"}}%  
```

```
Debug: internal, implementation, error 
    TypeError: reply[method](...).code is not a function
      at mc_utils.hash_password.hashed_password (multicolour-auth-jwt/index.js:99:96)
```

I also get an error with an Accept:vnd.api+json header
```
 TypeError: Uncaught error: Cannot read property 'uri' of null
    at Function.generate_payload [as application/vnd.api+json] (/.../multicolour-hapi-jsonapi/index.js:414:50)
```

**Comment by davemackintosh** [comment]
I'll look into this but first issue is your multipart/form-data payload in the post to `/session`.

Should look more like this instead of multipart:

```json
{
  "email": "adam@adam.co",
  "password": "password"
}
```

**Comment by davemackintosh** [comment]
https://www.npmjs.com/package/multicolour-hapi-jwt

**Comment by adam-cowley** [comment]
```
curl -X POST http://localhost:1811/session -d '{"email": "hello@newworld.codes","password":"password"}' -H "Accept:application/json"
```

`Unhandled rejection TypeError: get_decorator_for_apply_value(...)(...).code is not a function`

:(
